/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DJ {
  'id' : bigint,
  'bio' : string,
  'name' : string,
  'specialty' : string,
}
export interface Show {
  'endHour' : bigint,
  'hostName' : string,
  'dayOfWeek' : bigint,
  'description' : string,
  'showName' : string,
  'startHour' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDJ' : ActorMethod<[string, string, string], bigint>,
  'addShow' : ActorMethod<[Show], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllShows' : ActorMethod<[], Array<Show>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentShow' : ActorMethod<[], [] | [Show]>,
  'getDJs' : ActorMethod<[], Array<DJ>>,
  'getShowsForDay' : ActorMethod<[bigint], Array<Show>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeDJ' : ActorMethod<[bigint], undefined>,
  'removeShow' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];